<?php
    function triangle_tracker_menu() {
        $items= array();
        $items['triangle_tracker'] = array(
            'title' => "Triangle Tracker",
            'page callback' => 'drupal_get_form',
            'page arguments' => array('triangle_tracker_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['triangle_tracker_results'] = array(
            'title' => 'Your triangle Results',
            'page callback' => 'triangle_tracker_results',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function triangle_tracker_form() {
        $form['triangle_side_a'] = array(
            '#title' => 'Side A Length',
            '#type' => 'textfield',
            '#description' => t('Enter the length of side A'),
            '#element_validate' => array('element_validate_number', 'element_validate_integer_positive'),
            '#required' => TRUE,
        );
        $form['triangle_side_b'] = array(
            '#title' => 'Side B Length',
            '#type' => 'textfield',
            '#description' => t('Enter the length of side B'),
            '#element_validate' => array('element_validate_number', 'element_validate_integer_positive'),
            '#required' => TRUE,
        );
        $form['triangle_side_c'] = array(
            '#title' => 'Side C Length',
            '#type' => 'textfield',
            '#description' => t('Enter the length of side C'),
            '#element_validate' => array('element_validate_number', 'element_validate_integer_positive'),
            '#required' => TRUE,
        );
        $form['submit'] = array(
            '#value' => "GO!",
            '#type' => 'submit',
        );
        return $form;
    }

    function triangle_tracker_form_submit($form, &$form_state) {
        $side_a = $form_state['values']['triangle_side_a'];
        $side_b = $form_state['values']['triangle_side_b'];
        $side_c = $form_state['values']['triangle_side_c'];

        if (($side_a + $side_b) < $side_c || ($side_b + $side_c) < $side_a || ($side_a + $side_c) < $side_b) {
            drupal_set_message(t('It is not a triangle if the sum of two sides is less than the other side.'), $type = 'error');
        } else {
            $_SESSION['triangle_result'] = get_triangle($side_a, $side_b, $side_c);
            $form_state['redirect'] = 'triangle_tracker_results';
        }
    }

    function get_triangle($side_a, $side_b, $side_c) {
        if ($side_a == $side_b && $side_a == $side_c) {
            return "Equilateral";
        } elseif($side_a == $side_b || $side_a === $side_c || $side_b == $side_c) {
            return "Isosceles";
        } else {
            return "Scalene";
        }
    }

    function triangle_tracker_results() {
        return '<p>Your triangle is ' . $_SESSION['triangle_result'];
    }
